## Part 1: Explore the Data

Import the data and use Pandas to learn more about the dataset.

In [206]:
import pandas as pd

df = pd.read_csv('Resources/client_dataset.csv')
df.head()

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,item_id,category,subcategory,unit_price,unit_cost,unit_weight,qty,line_number
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,EUD29711-63-6U,decor,wall art,1096.80,762.71,7.50,105,1
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,XDA18116-89-4A,consumables,pens,24.95,15.09,1.49,21,0
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,ABE59463-05-7E,software,project management,13.52,7.86,1.68,39,6
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,ZMM00836-65-0C,consumables,pens,36.42,24.85,1.23,29,3
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,BZX55559-12-3X,consumables,misc,195.10,108.17,46.43,20,1

In [207]:
# View the column names in the data
print(df.columns)

Index(['first', 'last', 'job', 'phone', 'email', 'client_id', 'order_id',
       'order_date', 'order_week', 'order_year', 'item_id', 'category',
       'subcategory', 'unit_price', 'unit_cost', 'unit_weight', 'qty',
       'line_number'],
      dtype='object')

In [208]:
# Use the describe function to gather some basic statistics
print(df.describe)

<bound method NDFrame.describe of            first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308
1        Tiffany      Myers          Music therapist    201.442.4543x942
2        Shannon     Watson             Immunologist   687.737.9424x8503
3         Nathan      Baker    Accounting technician    827-788-8123x012
4      Christina   Schwartz             Chiropractor        265-829-3643
...          ...        ...                      ...                 ...
54634     Lauren      Reese           Radio producer  977.877.5272x11382
54635    Derrick      Moore                 Musician        358.661.5483
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339
54637      Wanda    Solomon             Toxicologist       (311)767-4924
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19
2                    swatson8146@payne.net      57113   1902144  2023-01-29
3                   bakernathan@benson.com      46554   9031802  2023-04-25
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28
...                                    ...        ...       ...         ...
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18
54638                     belld@galvan.com      24007   7489403  2023-01-04

       order_week  order_year         item_id     category  \
0              17        2023  EUD29711-63-6U        decor
1              20        2023  XDA18116-89-4A  consumables
2               4        2023  ABE59463-05-7E     software
3              17        2023  ZMM00836-65-0C  consumables
4              21        2023  BZX55559-12-3X  consumables
...           ...         ...             ...          ...
54634          17        2023  UCA28532-31-0B     software
54635           6        2023  EBD29277-23-7U  consumables
54636           9        2023  EBD30093-55-9Z  consumables
54637           3        2023  XMZ38239-49-3D    furniture
54638           1        2023  ZCZ05589-50-5D     software

              subcategory  unit_price  unit_cost  unit_weight   qty  \
0                wall art     1096.80     762.71         7.50   105
1                    pens       24.95      15.09         1.49    21
2      project management       13.52       7.86         1.68    39
3                    pens       36.42      24.85         1.23    29
4                    misc      195.10     108.17        46.43    20
...                   ...         ...        ...          ...   ...
54634           logistics       83.13      51.60         2.25    33
54635    kitchen supplies      206.59     175.46        11.70    47
54636   bathroom supplies       65.66      57.31         4.16   475
54637              stands        1.48       1.22        18.04   112
54638  project management        3.01       1.61         2.07  1031

       line_number
0                1
1                0
2                6
3                3
4                1
...            ...
54634            8
54635            0
54636            6
54637            0
54638            5

[54639 rows x 18 columns]>

In [209]:
# Use this space to do any additional research
# and familiarize yourself with the data.
df.head(30)

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,item_id,category,subcategory,unit_price,unit_cost,unit_weight,qty,line_number
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,EUD29711-63-6U,decor,wall art,1096.80,762.71,7.50,105,1
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,XDA18116-89-4A,consumables,pens,24.95,15.09,1.49,21,0
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,ABE59463-05-7E,software,project management,13.52,7.86,1.68,39,6
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,ZMM00836-65-0C,consumables,pens,36.42,24.85,1.23,29,3
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,BZX55559-12-3X,consumables,misc,195.10,108.17,46.43,20,1
5,Jessica,Reyes,"Production designer, theatre/television/film",5016915923,jessica.reyes@grimes.net,33615,1327730,2023-05-02,18,2023,BMB23158-88-9A,decor,plants,172.84,154.44,2.79,78,0
6,Brian,Moore,Barista,+1-893-400-2733x982,moore.official@martinez.com,87213,8080280,2023-04-19,16,2023,UAC50632-25-4E,consumables,kitchen supplies,245.56,231.95,1.73,56,5
7,Jesus,Wright,Theme park manager,605.947.9467x66513,wright.jesus.7579@meadows.com,46709,8946782,2023-02-14,7,2023,UEU25316-01-1U,consumables,pens,20.99,16.97,5.12,22,4
8,Rebecca,Brown,Chiropodist,665-955-0156x926,rbrown850@lewis.info,73362,9394118,2023-05-13,19,2023,DDA06248-98-7Z,consumables,paper products,83.86,59.00,0.27,49,3
9,Greg,Garcia,"Secretary, company",(231)342-7216x1421,ggarcia@bentley.biz,58789,9665852,2023-04-14,15,2023,DUU85042-87-5E,furniture,seating,66.88,54.15,2.47,78,1
10,Kyle,Williams,"Engineer, broadcasting (operations)",+1-432-234-2942,communitywilliams9024@taylor-padilla.biz,81012,5775924,2023-04-12,15,2023,DCD61783-36-6B,software,project management,520.00,457.16,4.92,98,0
11,Roberto,Howard,"Surveyor, land/geomatics",311.284.4575,roberto.howard.1290@davis-reese.info,74112,2859900,2023-02-06,6,2023,ZAE56533-39-8U,decor,wall art,4.22,3.65,1.82,211,6
12,Jessica,Reyes,"Production designer, theatre/television/film",5016915923,jessica.reyes@grimes.net,33615,6059361,2023-05-16,20,2023,BDC65078-60-7M,consumables,paper products,229.74,198.38,27.51,568,2
13,Patricia,Gould,Lobbyist,+1-694-749-5807x94968,newspapergould@walsh.biz,18145,3470698,2023-04-19,16,2023,AME10969-48-7D,consumables,paper products,33.72,30.08,2.01,44,0
14,Katherine,Taylor,"Psychologist, clinical",(943)632-3743x028,taylor.katherine.733@odonnell.org,48855,5953045,2023-05-11,19,2023,BXM59071-01-6D,electronics,computers,39.25,20.95,6.56,157,1
15,Matthew,Orozco,Research scientist (maths),+1-259-213-7449x4333,orozcomatthew@carr.com,67407,5014569,2023-04-09,14,2023,CCX95657-71-3B,decor,wall art,29.99,26.84,4.25,29,2
16,Joseph,Jordan,Government social research officer,680.657.3271x16477,jordan_joseph_4684@gibson.net,26185,2101230,2023-05-13,19,2023,ZEA01443-18-5A,furniture,stands,6.86,4.06,6.89,23,0
17,Carrie,Green,Colour technologist,+1-242-699-5329x474,c.green@oliver-smith.com,17355,4397711,2023-04-18,16,2023,CUU90642-03-7C,furniture,seating,33.41,26.82,29.12,49,0
18,David,Reyes,"Production assistant, television",714.475.3974,davidreyes@daniels.org,28523,6832072,2023-04-05,14,2023,UCX86104-19-0Z,consumables,misc,13.77,9.63,6.86,29,1
19,Shelby,Williams,Colour technologist,664.584.8160x389,williamstry70@armstrong.com,77184,7573941,2023-05-29,22,2023,ZDX29223-32-0B,consumables,paper products,199.05,183.99,8.11,233,4
20,Tricia,Stephenson,"Lecturer, further education",(978)811-8729x522,triciastephenson@vasquez.org,61603,7490302,2023-03-12,10,2023,ZAU36048-03-9A,furniture,tables,98.43,69.36,4.03,136,2
21,Patrick,Anderson,Commercial art gallery manager,947-812-9604x27025,andersonboard7205@delgado-hodge.org,51869,5020751,2023-03-16,11,2023,EZX36378-17-7A,consumables,bathroom supplies,53.17,39.52,4.18,52,4
22,Peter,Roberts,Architectural technologist,9238354425,roberts.peter@warren-sandoval.com,85413,3401371,2023-04-03,14,2023,UAU40137-77-3U,decor,plants,367.76,235.57,10.08,287,4
23,Christopher,Rhodes,"Engineer, manufacturing systems",001-319-767-5123,rhodeschristopher9096@alvarado.info,74159,6512694,2023-03-09,10,2023,ZMB00381-41-4E,electronics,audio visual,382.59,313.09,7.97,60,3
24,Glenn,Garcia,Textile designer,573.981.6374,determinegarcia5685@velasquez.com,33804,6024379,2023-01-26,4,2023,XZZ76042-95-6X,consumables,paper products,5.17,3.53,6.90,2163,2
25,Peter,Roberts,Architectural technologist,9238354425,roberts.peter@warren-sandoval.com,85413,9362283,2023-01-18,3,2023,BAD54487-56-3C,consumables,paper products,7.14,5.10,1.23,129944,4
26,Patrick,Anderson,Commercial art gallery manager,947-812-9604x27025,andersonboard7205@delgado-hodge.org,51869,8668707,2023-04-07,14,2023,UZZ84388-36-3B,consumables,pens,99.34,85.53,2.08,51,0
27,Jacob,Mendoza,Air cabin crew,+1-264-485-0270x066,jacobmendoza@johnson.biz,54932,5175749,2023-05-28,21,2023,DBE42716-07-1U,consumables,paper products,37.71,35.55,0.50,52,1
28,Tiffany,Lowe,Medical illustrator,001-755-263-0037x84650,lowetiffany3935@rodriguez.com,87125,8026387,2023-01-11,2,2023,UMC49136-12-1E,furniture,tables,210.12,137.62,16.90,54,4
29,Caleb,Rice,Technical brewer,868.703.3751x760,riceelse@collins.com,10643,1940019,2023-03-03,9,2023,EDU54097-48-4E,consumables,bathroom supplies,156.03,125.57,5.56,136,3

In [210]:
# What three item categories had the most entries?
category_item_count = df["category"].value_counts()
category_item_count.head(3)

category
consumables    23538
furniture      11915
software        8400
Name: count, dtype: int64

In [211]:
# For the category with the most entries, which subcategory had the most entries?
subcategory_find = df[df["category"] == "consumables"]
subcategory_count = subcategory_find['subcategory'].value_counts()

most_subcategory = subcategory_count.idxmax
most_subcategory

<bound method Series.idxmax of subcategory
bathroom supplies    6424
paper products       5874
kitchen supplies     5746
misc                 2891
pens                 2603
Name: count, dtype: int64>

In [212]:
# Which five clients had the most entries in the data?
client_count = df["client_id"].value_counts()

top_client_count = client_count.head(5)
top_client_count

client_id
33615    220
66037    211
46820    209
38378    207
24741    207
Name: count, dtype: int64

In [213]:
# Store the client ids of those top 5 clients in a list.
top_client_ids = top_client_count.index.tolist()

In [214]:
# How many total units (the qty column) did the client with the most entries order order?
most_buying_client = top_client_count.index[0]
client_find = df[df["client_id"] == most_buying_client]
order_amount = client_find["qty"].sum()
order_amount

64313

## Part 2: Transform the Data
Do we know that this client spent the more money than client 66037? If not, how would we find out? Transform the data using the steps below to prepare it for analysis.

In [215]:
# Create a column that calculates the subtotal for each line using the unit_price and the qty
df["subtotal"] = df["unit_price"] * df["qty"]

In [216]:
# Create a column for shipping price.
# Assume a shipping price of $7 per pound for orders over 50 pounds and $10 per pound for items 50 pounds or under.
df["shipping_price"] = df["unit_weight"] * df["qty"]
df["shipping_price"] = df["shipping_price"].apply(lambda x: 7 if x > 50 else 10)
df["shipping_price"] = df["shipping_price"].apply(lambda x: round(x, 2))

In [217]:
# Create a column for the total price using the subtotal and the shipping price along with a sales tax of 9.25%
df["total_price"] = df["subtotal"] + df["shipping_price"]
df["total_price"] = df["total_price"] + (df["total_price"] * 0.0925)
df["total_price"] = df["total_price"].apply(lambda x: round(x, 2))

In [218]:
# Create a column for the cost of each line using unit cost, qty, and
# shipping price (assume the shipping cost is exactly what is charged to the client).
df["cost"] = df["unit_cost"] * df["qty"] + df["shipping_price"]
df["cost"] = df["cost"].apply(lambda x: round(x, 2))

In [219]:
# Create a column for the profit of each line using line cost and line price
df["profit"] = df["total_price"] - df["cost"]
df.head(30)

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,...,unit_price,unit_cost,unit_weight,qty,line_number,subtotal,shipping_price,total_price,cost,profit
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,...,1096.80,762.71,7.50,105,1,115164.00,7,125824.32,80091.55,45732.77
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,...,24.95,15.09,1.49,21,0,523.95,10,583.34,326.89,256.45
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,...,13.52,7.86,1.68,39,6,527.28,7,583.70,313.54,270.16
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,...,36.42,24.85,1.23,29,3,1056.18,10,1164.80,730.65,434.15
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,...,195.10,108.17,46.43,20,1,3902.00,7,4270.58,2170.40,2100.18
5,Jessica,Reyes,"Production designer, theatre/television/film",5016915923,jessica.reyes@grimes.net,33615,1327730,2023-05-02,18,2023,...,172.84,154.44,2.79,78,0,13481.52,7,14736.21,12053.32,2682.89
6,Brian,Moore,Barista,+1-893-400-2733x982,moore.official@martinez.com,87213,8080280,2023-04-19,16,2023,...,245.56,231.95,1.73,56,5,13751.36,7,15031.01,12996.20,2034.81
7,Jesus,Wright,Theme park manager,605.947.9467x66513,wright.jesus.7579@meadows.com,46709,8946782,2023-02-14,7,2023,...,20.99,16.97,5.12,22,4,461.78,7,512.14,380.34,131.80
8,Rebecca,Brown,Chiropodist,665-955-0156x926,rbrown850@lewis.info,73362,9394118,2023-05-13,19,2023,...,83.86,59.00,0.27,49,3,4109.14,10,4500.16,2901.00,1599.16
9,Greg,Garcia,"Secretary, company",(231)342-7216x1421,ggarcia@bentley.biz,58789,9665852,2023-04-14,15,2023,...,66.88,54.15,2.47,78,1,5216.64,7,5706.83,4230.70,1476.13
10,Kyle,Williams,"Engineer, broadcasting (operations)",+1-432-234-2942,communitywilliams9024@taylor-padilla.biz,81012,5775924,2023-04-12,15,2023,...,520.00,457.16,4.92,98,0,50960.00,7,55681.45,44808.68,10872.77
11,Roberto,Howard,"Surveyor, land/geomatics",311.284.4575,roberto.howard.1290@davis-reese.info,74112,2859900,2023-02-06,6,2023,...,4.22,3.65,1.82,211,6,890.42,7,980.43,777.15,203.28
12,Jessica,Reyes,"Production designer, theatre/television/film",5016915923,jessica.reyes@grimes.net,33615,6059361,2023-05-16,20,2023,...,229.74,198.38,27.51,568,2,130492.32,7,142570.51,112686.84,29883.67
13,Patricia,Gould,Lobbyist,+1-694-749-5807x94968,newspapergould@walsh.biz,18145,3470698,2023-04-19,16,2023,...,33.72,30.08,2.01,44,0,1483.68,7,1628.57,1330.52,298.05
14,Katherine,Taylor,"Psychologist, clinical",(943)632-3743x028,taylor.katherine.733@odonnell.org,48855,5953045,2023-05-11,19,2023,...,39.25,20.95,6.56,157,1,6162.25,7,6739.91,3296.15,3443.76
15,Matthew,Orozco,Research scientist (maths),+1-259-213-7449x4333,orozcomatthew@carr.com,67407,5014569,2023-04-09,14,2023,...,29.99,26.84,4.25,29,2,869.71,7,957.81,785.36,172.45
16,Joseph,Jordan,Government social research officer,680.657.3271x16477,jordan_joseph_4684@gibson.net,26185,2101230,2023-05-13,19,2023,...,6.86,4.06,6.89,23,0,157.78,7,180.02,100.38,79.64
17,Carrie,Green,Colour technologist,+1-242-699-5329x474,c.green@oliver-smith.com,17355,4397711,2023-04-18,16,2023,...,33.41,26.82,29.12,49,0,1637.09,7,1796.17,1321.18,474.99
18,David,Reyes,"Production assistant, television",714.475.3974,davidreyes@daniels.org,28523,6832072,2023-04-05,14,2023,...,13.77,9.63,6.86,29,1,399.33,7,443.92,286.27,157.65
19,Shelby,Williams,Colour technologist,664.584.8160x389,williamstry70@armstrong.com,77184,7573941,2023-05-29,22,2023,...,199.05,183.99,8.11,233,4,46378.65,7,50676.32,42876.67,7799.65
20,Tricia,Stephenson,"Lecturer, further education",(978)811-8729x522,triciastephenson@vasquez.org,61603,7490302,2023-03-12,10,2023,...,98.43,69.36,4.03,136,2,13386.48,7,14632.38,9439.96,5192.42
21,Patrick,Anderson,Commercial art gallery manager,947-812-9604x27025,andersonboard7205@delgado-hodge.org,51869,5020751,2023-03-16,11,2023,...,53.17,39.52,4.18,52,4,2764.84,7,3028.24,2062.04,966.20
22,Peter,Roberts,Architectural technologist,9238354425,roberts.peter@warren-sandoval.com,85413,3401371,2023-04-03,14,2023,...,367.76,235.57,10.08,287,4,105547.12,7,115317.88,67615.59,47702.29
23,Christopher,Rhodes,"Engineer, manufacturing systems",001-319-767-5123,rhodeschristopher9096@alvarado.info,74159,6512694,2023-03-09,10,2023,...,382.59,313.09,7.97,60,3,22955.40,7,25086.42,18792.40,6294.02
24,Glenn,Garcia,Textile designer,573.981.6374,determinegarcia5685@velasquez.com,33804,6024379,2023-01-26,4,2023,...,5.17,3.53,6.90,2163,2,11182.71,7,12224.76,7642.39,4582.37
25,Peter,Roberts,Architectural technologist,9238354425,roberts.peter@warren-sandoval.com,85413,9362283,2023-01-18,3,2023,...,7.14,5.10,1.23,129944,4,927800.16,7,1013629.32,662721.40,350907.92
26,Patrick,Anderson,Commercial art gallery manager,947-812-9604x27025,andersonboard7205@delgado-hodge.org,51869,8668707,2023-04-07,14,2023,...,99.34,85.53,2.08,51,0,5066.34,7,5542.62,4369.03,1173.59
27,Jacob,Mendoza,Air cabin crew,+1-264-485-0270x066,jacobmendoza@johnson.biz,54932,5175749,2023-05-28,21,2023,...,37.71,35.55,0.50,52,1,1960.92,10,2153.23,1858.60,294.63
28,Tiffany,Lowe,Medical illustrator,001-755-263-0037x84650,lowetiffany3935@rodriguez.com,87125,8026387,2023-01-11,2,2023,...,210.12,137.62,16.90,54,4,11346.48,7,12403.68,7438.48,4965.20
29,Caleb,Rice,Technical brewer,868.703.3751x760,riceelse@collins.com,10643,1940019,2023-03-03,9,2023,...,156.03,125.57,5.56,136,3,21220.08,7,23190.58,17084.52,6106.06

## Part 3: Confirm your work
You have email receipts showing that the total prices for 3 orders. Confirm that your calculations match the receipts. Remember, each order has multiple lines.

Order ID 2742071 had a total price of \$152,811.89

Order ID 2173913 had a total price of \$162,388.71

Order ID 6128929 had a total price of \$923,441.25

In [ ]:
# Check your work using the totals above

## Part 4: Summarize and Analyze
Use the new columns with confirmed values to find the following information.

In [221]:
# How much did each of the top 5 clients by quantity spend? Check your work from Part 1 for client ids.
top_client_spend = df.groupby("client_id")["total_price"].sum()
top_client_spend = top_client_spend.loc[top_client_ids]
top_client_spend

client_id
33615     6380943.04
66037     8737039.74
46820     7995940.84
38378     9161581.67
24741    76669977.65
Name: total_price, dtype: float64

In [222]:
# Create a summary DataFrame showing the totals for the for the top 5 clients with the following information:
# total units purchased, total shipping price, total revenue, and total profit.
top_clients_df = df[df['client_id'].isin(top_client_ids)]
top_clients_totals = top_clients_df.groupby('client_id').agg(
    total_units=('qty', 'sum'),
    total_shipping=('shipping_price', 'sum'),
    total_revenue=('total_price', 'sum'),
    total_profit=('profit', 'sum')
)
top_clients_df.head()

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,...,unit_price,unit_cost,unit_weight,qty,line_number,subtotal,shipping_price,total_price,cost,profit
5,Jessica,Reyes,"Production designer, theatre/television/film",5016915923,jessica.reyes@grimes.net,33615,1327730,2023-05-02,18,2023,...,172.84,154.44,2.79,78,0,13481.52,7,14736.21,12053.32,2682.89
12,Jessica,Reyes,"Production designer, theatre/television/film",5016915923,jessica.reyes@grimes.net,33615,6059361,2023-05-16,20,2023,...,229.74,198.38,27.51,568,2,130492.32,7,142570.51,112686.84,29883.67
137,Bryan,Myers,Chief of Staff,444.233.9146x233,bmyers3696@wilson.com,46820,7109502,2023-05-12,19,2023,...,136.13,111.47,5.65,118,9,16063.34,7,17556.85,13160.46,4396.39
214,Bryan,Myers,Chief of Staff,444.233.9146x233,bmyers3696@wilson.com,46820,8967498,2023-02-06,6,2023,...,7.98,6.26,7.05,133,3,1061.34,7,1167.16,839.58,327.58
216,Angela,Everett,Osteopath,729-620-6192x875,aeverett@rodriguez.com,66037,1203693,2023-04-09,14,2023,...,301.87,166.09,0.26,157,2,47393.59,10,51788.42,26086.13,25702.29

In [223]:
top_clients_df.columns

Index(['first', 'last', 'job', 'phone', 'email', 'client_id', 'order_id',
       'order_date', 'order_week', 'order_year', 'item_id', 'category',
       'subcategory', 'unit_price', 'unit_cost', 'unit_weight', 'qty',
       'line_number', 'subtotal', 'shipping_price', 'total_price', 'cost',
       'profit'],
      dtype='object')

In [224]:
# Format the data and rename the columns to names suitable for presentation.
top_clients_totals.rename(columns={
    'total_units': 'Total Units Purchased',
    'total_shipping': 'Total Shipping Price',
    'total_revenue': 'Total Revenue',
    'total_profit': 'Total Profit'
}, inplace=True)

# Define the money columns. 
money_columns = ['Total Shipping Price', 'Total Revenue', 'Total Profit']

# Define a function that converts a dollar amount to millions.
def currency_format_millions(value):
    return f"${value / 1000000:.2f}M"
# Apply the currency_format_millions function to only the money columns. 
for col in money_columns:
    top_clients_totals[col] = top_clients_totals[col].apply(currency_format_millions)

# Rename the columns to reflect the change in the money format. 
top_clients_totals.rename(columns={
    'Total Shipping Price': 'Total Shipping Price (Millions)',
    'Total Revenue': 'Total Revenue (Millions)',
    'Total Profit': 'Total Profit (Millions)'
}, inplace=True)

In [225]:
top_clients_totals.columns

Index(['Total Units Purchased', 'Total Shipping Price (Millions)',
       'Total Revenue (Millions)', 'Total Profit (Millions)'],
      dtype='object')

In [226]:
# Sort the updated data by "Total Profit (millions)" form highest to lowest and assign the sort to a new DatFrame.
top_clients_totals = top_clients_totals.sort_values('Total Profit (Millions)', ascending=False)
top_clients_totals.head()

,Total Units Purchased,Total Shipping Price (Millions),Total Revenue (Millions),Total Profit (Millions)
client_id,,,,
24741,239862,$0.00M,$76.67M,$36.11M
66037,43018,$0.00M,$8.74M,$3.13M
38378,73667,$0.00M,$9.16M,$2.95M
46820,75768,$0.00M,$8.00M,$2.59M
33615,64313,$0.00M,$6.38M,$2.03M